# Generated by Django 6.0.2 on 2026-04-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usern', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('itemn', models.CharField(max_length=50)),
                ('item_id', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
